### ISSUE TITLE
stea_input should maybe not use argparse

### ISSUE THREAD

**Issue by berland** [equinor/fmu-steaclient#23]
If stea_input is not meant to be an endpoint for users, it should not use argparse for its API.

**Comment by berland** [comment]
Beware, when this is changed we probably break existing scripts.

**Comment by markusdregi** [comment]
Thanks for the feedback! There is not that much activity on STEA right now, but perhaps we can increase the effort later. It is also a bit unclear whether we have any funding for this project as of now...

**Comment by xjules** [comment]
Now it's using click.
