### ISSUE TITLE
Rename this repository

### ISSUE THREAD

**Issue by bpthrane** [equinor/fmu-steaclient#41]
STEA is known internally in Equinor as the Windows desktop application used for economic analysis. The name for this repository should therefore not be stea, but a name that reflects what the application is. This repository contains code for a http client for the REST API interface that STEA exposes for calculating STEA projects stored in the STEA database. In the STEA software suite, the application is called STEA calculation service. So maybe a name should have some of these terms: stea http calculation client service fmu.

Please consider renaming this repository. In the long term, the STEA development team will migrate the source code to Github and it would be natural to use the "stea" name on Github.

**Comment by xjules** [comment]
It's a good idea. Nevertheless, we need to firstly find out the impact of changing the name. So we get back to you.

**Comment by berland** [comment]
Suggestion for new repo name: `fmu-steaclient`. If later also the Python package name is changed, it can either be `fmu_steaclient` or `fmu.steaclient` (joining the existing `fmu` namespace). The current package is not FMU specific, but it is the only known usage of it (correct me if wrong). 

Renaming to include `fmu` also hints to the possibility for merging in the associated fmu forward model from https://github.com/equinor/semeio/blob/main/semeio/jobs/scripts/fm_stea.py

**Comment by bpthrane** [comment]
Sounds good!
